services:
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - docker_network

volumes:
    postgres_data: 

networks:
  docker_network:
    driver: bridge