services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - ../.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - .././customer:/csv
      - .././item:/item
    networks:
      - docker_network

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - docker_network

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python
    restart: no
    env_file:
      - ../.env
    volumes:
      - .././:/app
    working_dir: /app
    networks:
      - docker_network

volumes:
  postgres_data:

networks:
  docker_network:
    driver: bridge
